n_atoms: 118
n_bonds: 5
emb_dim: 120
nlayers: 6
max_nodes: 250
max_edges: 500
missing_value: -1
n_node_features: 133
n_edge_features: 14
n_class_tokens: 1
encoder_class: "DFSCodeEncoderLSTM"
dropout: 0.
bidirectional: true
