model:
    n_atoms: 118
    n_bonds: 5
    emb_dim: 120
    nhead: 12
    nlayers: 6
    max_nodes: 250
    max_edges: 500
    dim_feedforward: 2048
    missing_value: -1
    n_node_features: 133
    n_edge_features: 14
    
    
data:
    n_files: 10
    n_splits: 1
    n_iter_per_split: 1
    #path: "/home/wendlerc/noH/timeout60_4/"
    path: "./results/pubchem/noH/10K"
    batch_size: 50
    
training:
    mode: min2min
    fraction_missing: 0.15
    lr: 0.00003
    n_epochs: 10000
    lr_adjustment_period: 500
    lr_patience: 5
    decay_factor: 0.8
    minimal_lr: 0.00000006
    batch_size: 50
    accumulate_grads: 1
    gpu_id: 0
    es_patience: 100
    es_improvement: 0.0
    pretrained_dir: null
    es_path: null
    load_last: True
    
    

    
    




