model:
    n_atoms: 118
    n_bonds: 5
    emb_dim: 120
    nhead: 12
    nlayers: 6
    max_nodes: 250
    max_edges: 500
    dim_feedforward: 2048
    missing_value: -1
    n_node_features: 133
    n_edge_features: 14
    n_class_tokens: 1
     
data:
    n_files: 10
    n_splits: 1
    n_iter_per_split: 10000
    #path: "/home/wendlerc/noH/timeout60_4/"
    path: "./results/pubchem/noH/10K/"
    valid_path: "./results/pubchem/noH/validation/"
    batch_size: 50
    
training:
    mode: min2min
    fraction_missing: 0.15
    lr: 0.00003
    n_epochs: 10000
    lr_adjustment_period: 500
    lr_patience: 5
    decay_factor: 0.8
    minimal_lr: 0.00000006
    batch_size: 50
    accumulate_grads: 2
    gpu_id: 0
    es_patience: 100
    es_improvement: 0.0
    pretrained_dir: null
    es_path: null
    load_last: True
    
finetune:
    data_dir_pattern: "./datasets/mymoleculenet/%s/"
    load_dir_pattern: "./results/mymoleculenet_plus_features/%s/1/"
    model_dir_pattern: "./models/%s/"
    lr: 0.003
    #lr: 0.000003
    weight_decay: 0.1
    clip_gradient: 0.5
    n_epochs: 25
    lr_patience: 3
    decay_factor: 0.8
    minimal_lr: 0.00000006
    batch_size: 50
    accumulate_grads: 2
    gpu_id: 0
    es_patience: 10
    es_improvement: 0.0
    pretrained_project: 'pubchem-bert'
    pretrained_entity: 'chrisxx'
    pretrained_model: 'bert-4-10M'
    es_path: null
    load_last: True
    use_min: True
    fingerprint: 'cls' # mean, max, sum, cls-mean-max
    strict: True
    dataset: 'bbbp'
    seed: 123
    
    
    
    
    

    
    




