wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.9
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.8.9
      5: 0.10.33
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 128
factor:
  desc: null
  value: 0.9
lr:
  desc: null
  value: 0.0003
n_epochs:
  desc: null
  value: 10000
n_train:
  desc: null
  value: 110000
n_valid:
  desc: null
  value: 10000
patience:
  desc: null
  value: 5
target_idx:
  desc: null
  value: 7
