n_atoms: 118
n_bonds: 5
emb_dim: 120
nhead: 12
nlayers: 6
max_nodes: 250
max_edges: 500
dim_feedforward: 2048
missing_value: null
n_node_features: 133
n_edge_features: 14
n_class_tokens: 1
encoder_class: "DFSCodeEncoderConcat"
rescale_flag: true     
