data:
  batch_size: 50
  n_iter_per_split: 1
  n_used: 3
  path: ./results/pubchem/noH/10K/
  valid_path: ./results/pubchem/noH/validation/
finetune:
  accumulate_grads: 2
  batch_size: 50
  clip_gradient: 0.5
  data_dir_pattern: ./datasets/mymoleculenet/%s/
  dataset: bbbp
  decay_factor: 0.8
  es_improvement: 0.0
  es_path: null
  es_patience: 10
  fingerprint: cls
  gpu_id: 0
  load_dir_pattern: ./results/mymoleculenet_plus_features/%s/1/
  load_last: true
  lr: 0.003
  lr_patience: 3
  minimal_lr: 6.0e-08
  model_dir_pattern: ./models/%s/
  n_epochs: 25
  pretrained_entity: chrisxx
  pretrained_model: bert-100K
  pretrained_project: pubchem-bert
  seed: 123
  strict: true
  use_min: true
  weight_decay: 0.1
model:
  dim_feedforward: 2048
  emb_dim: 120
  max_edges: 500
  max_nodes: 250
  missing_value: null
  n_atoms: 118
  n_bonds: 5
  n_class_tokens: 1
  n_edge_features: 14
  n_node_features: 133
  nhead: 12
  nlayers: 6
training:
  accumulate_grads: 2
  batch_size: 50
  decay_factor: 0.8
  es_improvement: 0.0
  es_path: null
  es_patience: 100
  gpu_id: 0
  load_last: true
  lr: 0.0003
  lr_adjustment_period: 500
  lr_patience: 5
  minimal_lr: 6.0e-08
  n_epochs: 1
  pretrained_dir: null
